{{- if .Values.dockerRegistry.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.dockerRegistry.secretName }}
  labels:
    {{- include "jenkins.labels" . | nindent 4 }}
type: Opaque
data:
  jenkins-admin-password: {{  .Values.dockerRegistry.user | b64enc| quote  }}
  jenkins-admin-user: {{ .Values.dockerRegistry.password | b64enc | quote }}
{{ end }}